apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  egress:
    - hosts:
        - "./*"
        - "{{ .Release.Namespace }}/*"
