{{- if .Values.argoRollouts.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.name" . }}-canary
  namespace: {{ template "application.namespace" $ }}
  labels:
{{ include "application.labels.unevenlabs" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.service.additionalLabels }}
{{ toYaml .Values.service.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  selector:
{{ include "application.labels.selector" . | indent 4 }}
{{- if .Values.deployment.podLabels }}
{{ toYaml .Values.deployment.podLabels | indent 4 }}
{{- end }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
{{ end }}
