{{- if and .Values.rbac.enabled .Values.rbac.clusterroles }}
{{- range .Values.rbac.clusterroles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{ include "application.labels.unevenlabs" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
{{- if $.Values.rbac.additionalLabels }}
{{ toYaml $.Values.rbac.additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.rbac.annotations }}
  annotations:
{{ toYaml $.Values.rbac.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" $ }}-clusterrole-{{ .name }}
rules:
{{ toYaml .rules | indent 2 }}
---
{{- end }}
{{- end }}
