{{- if .Values.configMap }}
{{- if .Values.configMap.enabled }}
{{- range .Values.configMap.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "application.labels.unevenlabs" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
{{- if .additionalLabels }}
{{ toYaml .additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.configMap.additionalLabels }}
{{ toYaml $.Values.configMap.additionalLabels | indent 4 }}
{{- end }}
{{- if or ($.Values.configMap.annotations) (.annotations) }}
  annotations:
{{- end }}
{{- if .annotations }}
{{ toYaml .annotations | indent 4 }}
{{- end }}
{{- if $.Values.configMap.annotations }}
{{ toYaml $.Values.configMap.annotations | indent 4 }}
{{- end }}
  {{- if eq .nameSuffix ""  }}
  name: {{ template "application.name" $ }}
  {{- else }}
  name: {{ template "application.name" $ }}-{{ .nameSuffix }}
  {{- end }}
  namespace: {{ template "application.namespace" $ }}
data:
{{ toYaml .data | indent 2 }}
---
{{- end }}
{{- end }}
{{- end }}
