{{- if and .Values.keda.enabled .Values.keda.scaledObjects}}
{{- range .Values.keda.scaledObjects }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .name }}
  labels:
{{ include "application.labels.unevenlabs" $ | indent 4 }}
{{ include "application.labels.chart"   $ | indent 4 }}
spec:
  scaleTargetRef:
  {{- toYaml .scaleTargetRef | nindent 4}}
  pollingInterval:  {{ .pollingInterval | default 30  }}
  cooldownPeriod:   {{ .cooldownPeriod  | default 300 }}
  minReplicaCount:  {{ .minReplicaCount | default 1   }}
  maxReplicaCount:  {{ .maxReplicaCount | default 100 }}
  {{- if .fallback }}
  fallback:
  {{- toYaml .fallback | nindent 4}}
  {{- end }}
  {{- if .advanced }}
  advanced:
  {{- toYaml .advanced | nindent 4}}
  {{- end }}
  triggers:
  # {list of triggers to activate scaling of the target resource}
  {{- toYaml .triggers | nindent 2}}
---
{{- end }}
{{- end }}
