{{- if and .Values.rbac.enabled .Values.rbac.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "application.labels.unevenlabs" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.rbac.serviceAccount.additionalLabels }}
{{ toYaml .Values.rbac.serviceAccount.additionalLabels | indent 4 }}
{{- end }}
{{- if or .Values.rbac.serviceAccount.annotations }}
  annotations:
  {{- if .Values.rbac.serviceAccount.annotations }}
{{ toYaml .Values.rbac.serviceAccount.annotations | indent 4 }}
  {{- end }}
{{- end }}
  namespace: {{ template "application.namespace" . }}
{{- if .Values.rbac.serviceAccount.name }}
  name: {{ .Values.rbac.serviceAccount.name }}
{{- else }}
  name: {{ template "application.name" . }}
{{- end }}
{{- end }}
