{{- if .Values.vault }}
{{- if .Values.vault.secretsFile }}
{{- if .Values.vault.secretsFile.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "application.labels.unevenlabs" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
{{- if $.Values.vault.secretsFile.additionalLabels }}
{{ toYaml $.Values.vault.secretsFile.additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.vault.secretsFile.annotations }}
  annotations:
{{ toYaml $.Values.vault.secretsFile.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" $ }}-vault-secret-files
  namespace: {{ template "application.namespace" $ }}
data:
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/{{ .Values.vault.path }}"
        config = {
          role = "{{ .Values.vault.role }}"
        }
      }
    }

  {{- $indexOfLastItem := sub (len .Values.vault.secretsFile.files) 1 }}
  {{- $restartCommand := .Values.vault.secretsFile.restartCommand }}
  {{- range $index, $item := .Values.vault.secretsFile.files }}
    template {
    {{- if $item.contents }}
      contents = <<EOH
        {{ `{{-` }} with secret "{{- $item.secretPath }}" {{- ` }}` }}
      {{- range $secret := $item.contents }}
        {{ $secret.name }}: {{ `{{` }} {{ $secret.value }} {{ `}}` }}
      {{- end }}
        {{ `{{- end }}`}}
      EOH
    {{- else }}
      contents = <<EOH
        {{ `{{-` }} with secret "{{- $item.secretPath }}" {{- ` }}` }}
          {{ `{{-` }} .Data.data.{{- $item.secretKey }} {{- ` }}` }}
        {{ `{{- end }}` }}
      EOH
    {{- end }}
    {{- if eq (substr 0 1 $item.mountPath) "/" }}
      destination = "/vault/secrets{{ $item.mountPath }}"
    {{- else }}
      destination = "/vault/secrets/{{ $item.mountPath }}"
    {{- end }}
    {{- if $item.command }}
      command = {{ $item.command | quote }}
    {{- else if and (eq $index $indexOfLastItem) $restartCommand }}
      command = {{ $restartCommand | quote }}
    {{- end }}
    }
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
