apiVersion: v2
appVersion: v0.6.0
description: A Helm chart for kafka-UI
icon: https://github.com/provectus/kafka-ui/raw/master/documentation/images/kafka-ui-logo.png
name: kafka-ui
type: application
version: 0.6.0-1
