apiVersion: v2
name: cost-analyzer
description: cost-analyzer
type: application
version: 2.4.3-1
dependencies:
  - name: cost-analyzer
    version: 2.4.3
    repository: oci://public.ecr.aws/kubecost
