name: retool
apiVersion: v2
appVersion: 1.0.0
version: 1.0.0
description: Retool at Unevenlabs
keywords:
  - Retool
  - Unevenlabs
maintainers:
  - email: filipe@unevenlabs.com
    name: Filipe
dependencies:
  - name: retool
    version: 6.4.10
    repository: https://charts.retool.com
    condition: retool.enabled
