retool:
  enabled: true

  config:
    encryptionKey: "replaceme"

  image:
    tag: "3.114.22-stable"

  ingress:
    enabled: false

  postgresql:
    enabled: false

  workflows:
    enabled: false

  retool-temporal-services-helm:
    enabled: false

virtualService:
  enabled: true
  gateways: ["default/default-gateway"]
  annotations: {}
  hosts: []
  whiteListed:
    ips: []

service:
  port: 3000
