annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Multiple sources for Application and ApplicationSet
apiVersion: v2
description: A Helm chart for managing additional Argo CD Applications and Projects
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
  - argoproj
  - argocd
  - gitops
maintainers:
  - name: argoproj
    url: https://argoproj.github.io/
name: argocd-apps
type: application
version: 0.0.9
