annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Switch from full fork to upstream dependency
apiVersion: v2
description: Wrapper chart for argocd-apps, managing Argo CD Applications and Projects
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
  - argoproj
  - argocd
  - gitops
maintainers:
  - name: argoproj
    url: https://argoproj.github.io/
name: argocd-apps
dependencies:
- name: argocd-apps
  version: "2.0.4"
  repository: "https://argoproj.github.io/argo-helm"
version: 2.0.4-1
