apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: retool-postgresql
  namespace: retool
spec:
  databases:
    retool: retool
  numberOfInstances: 1
  patroni:
    pg_hba:
    - local   all             all                             trust
    - hostssl all             +zalandos    127.0.0.1/32       pam
    - host    all             all          127.0.0.1/32       md5
    - hostssl all             +zalandos    ::1/128            pam
    - host    all             all          ::1/128            md5
    - local   replication     standby                         trust
    - hostssl replication     standby      all                md5
    - hostssl all             +zalandos    all                pam
    - hostssl all             all          all                md5
    - host    all             all          all                md5
  postgresql:
    version: "16"
  teamId: retool
  users:
    retool:
    - superuser
    - createdb
  volume:
    size: 50Gi
status:
  PostgresClusterStatus: Running
