{{- if .Values.datadogMonitors.opensea_unauthorized_api_key_errors.enabled -}}
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: {{ template "application.name" $ }}-opensea-unauthorized-api-key-errors
  namespace: {{ template "application.namespace" $ }}
  labels:
{{ include "application.labels.unevenlabs" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
spec:
  name: {{ .Values.environment }} - {{ title .Values.chain_name }} - Opensea Unauthorized API Key Errors
  type: log alert
  query: logs("@topic:opensea-unauthorized-api-key service:indexer-v5-{{ .Values.chain_name }} env:{{ .Values.environment }}").index("*").rollup("count").last("5m") > 1
  message: |-
    @slack-alerts @backend@unevenlabs.com

    @pagerduty-indexer

  options:
    thresholds:
      critical: "0"
    enableLogsSample: false
    notifyAudit: false
    onMissingData: default
    includeTags: true

  tags:
    - Application:{{ .Values.labels.application }}
    - Chain:{{ .Values.labels.chain }}
    - Environment:{{ .Values.labels.environment }}
    - Owner:{{ .Values.labels.owner }}
    - K8sPath:{{ .Template.Name }}
    - generated:kubernetes
{{- end -}}
