{{- if .Values.datadogMonitors.processed_seaport_orders_anomaly_alarm.enabled -}}
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: {{ template "application.name" $ }}-processed-seaport-orders-anomaly
  namespace: {{ template "application.namespace" $ }}
  labels:
{{ include "application.labels.unevenlabs" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
spec:
  name: {{ .Values.environment }} - {{ title .Values.chain_name }} - Processed Seaport Orders Anomaly
  type: query alert
  query: avg(last_12h):anomalies(sum:ingestedOrdersV2{service:indexer-v5-{{ .Values.chain_name }},env:{{ .Values.environment }},orderkind:seaport*}.as_count(), 'basic', 3, direction='below', interval=120, alert_window='last_30m', count_default_zero='true') >= 1
  message: |-
    Part of composite monitor

  options:
    thresholds:
      critical: "1"
      criticalRecovery: "0"
    notifyAudit: false
    requireFullWindow: false
    notifyNoData: false
    renotifyInterval: 0
    includeTags: true

    thresholdWindows:
      triggerWindow: "last_30m"
      recoveryWindow: "last_15m"

  tags:
    - Application:{{ .Values.labels.application }}
    - Chain:{{ .Values.labels.chain }}
    - Environment:{{ .Values.labels.environment }}
    - Owner:{{ .Values.labels.owner }}
    - K8sPath:{{ .Template.Name }}
    - generated:kubernetes
---
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: {{ template "application.name" $ }}-opensea-websocket-events-anomaly
  namespace: {{ template "application.namespace" $ }}
  labels:
{{ include "application.labels.unevenlabs" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
spec:
  name: {{ .Values.environment }} - {{ title .Values.chain_name }} - Opensea Websocket Events Anomaly
  type: query alert
  query: avg(last_12h):anomalies(sum:openseaReceivedOrderEvents{service:indexer-v5-{{ .Values.chain_name }},env:{{ .Values.environment }},issupported:true}.as_count(), 'basic', 3, direction='below', interval=120, alert_window='last_30m', count_default_zero='true') >= 1
  message: |-
    Part of composite monitor

  options:
    thresholds:
      critical: "1"
      criticalRecovery: "0"
    notifyAudit: false
    requireFullWindow: false
    notifyNoData: false
    renotifyInterval: 0
    includeTags: true

    thresholdWindows:
      triggerWindow: "last_30m"
      recoveryWindow: "last_15m"

  tags:
    - Application:{{ .Values.labels.application }}
    - Chain:{{ .Values.labels.chain }}
    - Environment:{{ .Values.labels.environment }}
    - Owner:{{ .Values.labels.owner }}
    - K8sPath:{{ .Template.Name }}
    - generated:kubernetes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "application.name" $ }}-processed-seaport-orders-anomaly-composite
  namespace: {{ template "application.namespace" $ }}
  labels:
    datadog-operator-extra: "true"
{{ include "application.labels.unevenlabs" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
data:
  composite: <{{ template "application.name" $ }}-processed-seaport-orders-anomaly> && !<{{ template "application.name" $ }}-opensea-websocket-events-anomaly>
  body: |-
    name: {{ .Values.environment }} - {{ title .Values.chain_name }} - Processed Seaport Orders Anomaly Composite
    type: composite
    query:
    message: |-
      This alarm fires if we experience an unusual drop in Seaport order processing
      - Check related queues to determine if there are any delays or buffering responsible for fewer orders processed
      - Check Opensea Websocket Metrics

      @slack-alerts @backend@unevenlabs.com @pagerduty-indexer

    options:
      thresholds:
        critical: null
      notifyAudit: false
      requireFullWindow: false
      notifyNoData: false
      renotifyInterval: 0
      includeTags: true

    tags:
      - Application:{{ .Values.labels.application }}
      - Chain:{{ .Values.labels.chain }}
      - Environment:{{ .Values.labels.environment }}
      - Owner:{{ .Values.labels.owner }}
      - K8sPath:{{ .Template.Name }}
      - generated:kubernetes
{{- end -}}
