{{- range .Values.virtualService }}
{{- if .whiteListed }}
{{- if has "AuthorizationPolicy" .type }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .name }}
  labels:
    {{- include "yopass.labels" $ | nindent 4 }}
spec:
{{- if .whiteListed.matchLabels }}
  selector:
    matchLabels:
      {{- toYaml .whiteListed.matchLabels | nindent 6 }}
{{- end }}
  action: ALLOW
  rules:
{{- if .whiteListed.releaseNamespace }}
  - from:
    - source:
        namespaces:
        - {{ $.Release.Namespace }}
{{- end }}
  - from:
    - source:
        remoteIpBlocks:
{{- range .whiteListed.ips }}
          - {{ . | quote }}
{{- end }}
    to:
    - operation:
        hosts:
{{- range .hosts }}
          - {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
