{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "kafka-ui.fullname" . }}
  annotations:
  {{- range $key, $value := .Values.virtualService.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  gateways: {{ .Values.virtualService.gateways }}
  hosts: {{ .Values.virtualService.hosts }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host:  {{ include "kafka-ui.fullname" . }}
        port:
          number: {{ .Values.service.port }}
      weight: 100
{{- end }}
