{{- if .Values.beats }}
{{- range $beatsInstance := .Values.beats }}
{{- if (and (eq $beatsInstance.spec.type "filebeat") $beatsInstance.spec.cloudwatchServiceAccount) }}
{{- range $k, $v := $beatsInstance.spec.config }}
{{- if eq $k "filebeat.inputs" }}
{{- range $inputs := $v }}
{{- if (and $inputs.type (eq $inputs.type "aws-cloudwatch")) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $beatsInstance.spec.cloudwatchServiceAccount.name }}
  namespace: {{ $.Release.Namespace }}
  annotations: 
    "eks.amazonaws.com/role-arn": {{ $beatsInstance.spec.cloudwatchServiceAccount.roleArn }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
