{{- if .Values.elasticsearch }}
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elasticsearch.name | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    Environment: {{ .Values.elasticsearch.labels.Environment | default "dev" }}
spec:
  version: {{ .Chart.AppVersion }}
  {{- if .Values.elasticsearch.spec.volumeClaimDeletePolicy }}
  volumeClaimDeletePolicy: {{ .Values.elasticsearch.spec.volumeClaimDeletePolicy }}
  {{- end }}
  http:
    tls:
      selfSignedCertificate:
        disabled: {{ .Values.elasticsearch.spec.disableTls }}
  nodeSets:
  {{- range .Values.elasticsearch.spec.nodeSets }}
  - name: {{ .name | default "default" }}
    count: {{ .count | default 3 }}
    config: {{ toYaml .config | nindent 6 }}
    podTemplate:
      metadata:
        labels:
          Environment: {{ $.Values.elasticsearch.labels.Environment | default "dev" }}
      {{- if $.Values.elasticsearch.additionalPodAnnotations }}
        annotations: {{ toYaml $.Values.elasticsearch.additionalPodAnnotations | nindent 10 }}
      {{- end }}
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: xpack.security.enabled
            value: "false"
          - name: READINESS_PROBE_PROTOCOL
            value: http
        {{- if $.Values.elasticsearch.spec.awsRoleArn }}
          - name: AWS_WEB_IDENTITY_TOKEN_FILE
            value: "/usr/share/elasticsearch/config/repository-s3/aws-web-identity-token-file"
          - name: AWS_ROLE_ARN
            value: {{ $.Values.elasticsearch.spec.awsRoleArn }}
          volumeMounts:
            - name: aws-iam-token
              mountPath: /usr/share/elasticsearch/config/repository-s3
        {{- end }}
          resources:
            limits:
              cpu: {{ .resources.limits.cpu | default 2 }}
              memory: {{ .resources.limits.memory | default "2Gi" }}
            requests:
              cpu: {{ .resources.requests.cpu | default "100m" }}
              memory: {{ .resources.requests.memory | default "1Gi" }}
      {{- if $.Values.elasticsearch.spec.awsRoleArn }}
        serviceAccountName: {{ $.Values.elasticsearch.name | default $.Release.Name }}-aws-sa
        volumes:
          - name: aws-iam-token
            projected:
              sources:
                - serviceAccountToken:
                    audience: sts.amazonaws.com
                    expirationSeconds: 86400
                    path: aws-web-identity-token-file
      {{- end }}
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
        spec:
          # If not specified, will use the default storage class.
          accessModes:
          - {{ .accessModes | default "ReadWriteOnce" }}
          resources:
            requests:
              storage: {{ .storage | default "100Gi" }}
          {{- if .storageClassName }}
          storageClassName: {{ .storageClassName }}
          {{- end }}
  {{- end }}
  podDisruptionBudget:
    spec:
      {{- with .Values.elasticsearch.spec.podDisruptionBudget }}
      minAvailable: {{ .minAvailable }}
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: {{ $.Values.elasticsearch.name | default $.Release.Name }}
  {{- end}}
{{- end }}
