{{- $saname := printf "%s-%s" ( include "eck.fullname" . ) "filebeat-container-logs" -}}
{{- $rolename := printf "%s-%s" ( include "eck.fullname" . ) "filebeat-container-logs-cluster-role" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $rolename }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: filebeat
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
    verbs:
      - get
      - watch
      - list
  - nonResourceURLs: ["*"]
    verbs:
      - get
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saname }}
  namespace: {{.Release.Namespace}}
  labels:
    app: filebeat
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $rolename }}-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app: filebeat
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
roleRef:
  kind: ClusterRole
  name: {{ $rolename }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ $saname }}
  namespace: {{ .Release.Namespace }}
