---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-container-logs
  namespace: {{ .Release.Namespace }}
  labels:
    app: filebeat
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
