{{- if .Values.webapp.virtualService.enabled }}
{{- if .Values.webapp.virtualService.whiteListed.ips }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.webapp.virtualService.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: webapp
  action: ALLOW
  rules:
{{- if .Values.webapp.virtualService.whiteListed.internalIPs }}
  - from:
    - source:
        remoteIpBlocks:
  {{- range .Values.webapp.virtualService.whiteListed.internalIPs }}
          - {{ . | quote }}
  {{- end }}
{{- end }}
  - from:
    - source:
        remoteIpBlocks:
{{- range .Values.webapp.virtualService.whiteListed.ips }}
          - {{ . | quote }}
{{- end }}
    to:
    - operation:
        hosts:
{{- range .Values.webapp.virtualService.hosts }}
          - {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
