{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "apache-nifi.fullname" . }}
spec:
  host: {{ template "apache-nifi.fullname" . }}
  trafficPolicy:
    tls:
      mode: SIMPLE
{{- end }}
