{{- if .Values.datadogMonitors }}
{{- range $datadogMonitor := .Values.datadogMonitors }}
---
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: {{ template "application.name" $ }}-{{ $datadogMonitor.name }}
  namespace: {{ template "application.namespace" $ }}
  labels:
{{ include "application.labels.unevenlabs" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
spec:
	name: Expired orders update failure
	type: log alert
	query: logs("@service:indexer-v5-mainnet Failed to handle expired orders").index("*").rollup("count").last("5m") > 1
	message: |
	  - Check the [error logs](https://app.datadoghq.com/logs?query=%22Failed%20to%20handle%20expired%20orders%22%20&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1681743766622&to_ts=1684335766622&live=true)
		for any obvious errors\n\n@slack-alerts @backend@unevenlabs.com\n\n{{#is_alert_recovery}}\n@pagerduty-indexer

		{{/is_alert_recovery}}
	tags: []
	options:
		thresholds:
			critical: 1
		enable_logs_sample: true
		notify_audit: false
		restriction_query:
		on_missing_data: default
		include_tags: true
		escalation_message: "@pagerduty-indexer"
		renotify_interval: 30
		renotify_statuses:
		- alert
		- no data
		renotify_occurrences: 1
		new_host_delay: 300
		groupby_simple_monitor: false
		silenced: {}
	priority:
	restricted_roles:
{{- end }}
{{- end }}

{
	"id": 68832083,
	"name": "Expired orders update failure",
	"type": "log alert",
	"query": "logs(\"@service:indexer-v5-mainnet Failed to handle expired orders\").index(\"*\").rollup(\"count\").last(\"5m\") > 1",
	"message": "- Check the [error logs](https://app.datadoghq.com/logs?query=%22Failed%20to%20handle%20expired%20orders%22%20&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1681743766622&to_ts=1684335766622&live=true) for any obvious errors\n\n@slack-alerts @backend@unevenlabs.com\n\n{{#is_alert_recovery}}\n@pagerduty-indexer \n{{/is_alert_recovery}}",
	"tags": [],
	"options": {
		"thresholds": {
			"critical": 1
		},
		"enable_logs_sample": true,
		"notify_audit": false,
		"restriction_query": null,
		"on_missing_data": "default",
		"include_tags": true,
		"escalation_message": "@pagerduty-indexer",
		"renotify_interval": 30,
		"renotify_statuses": [
			"alert",
			"no data"
		],
		"renotify_occurrences": 1,
		"new_host_delay": 300,
		"groupby_simple_monitor": false,
		"silenced": {}
	},
	"priority": null,
	"restricted_roles": null
}
