labels:
  Environment: dev
  Owner: INFRASTRUCTURE
  Application: ECK

# To deploy an Elasticsearch instance
# For more settings, see https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elasticsearch-specification.html
elasticsearch:
  name: elasticsearch
  labels:
    Environment: dev
  spec:
    disableTls: true
    # awsRoleArn: arn:aws:iam::121212121212:role/dev-eck
    nodeSets:
      - name: default
        config:
          node.store.allow_mmap: false
          # Specify node roles
          # node.roles: ["master"]
        count: 3
        storage: 200Gi
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
    podDisruptionBudget:
      minAvailable: 2

# To deploy a Beat instance
# For more settings, see https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-beat.html
beats:
  - name: filebeat-container-logs
    labels:
      Environment: dev
    spec:
      # Beat has multiple types, e.g. Filebeat, Metricbeat, Heartbeat. Specify the desired type below.
      type: filebeat
      # The Elasticsearch instance Beat should try to connect to.
      elasticsearchRef:
        name: elasticsearch
      config:
        filebeat.inputs:
          - type: container
            paths:
              - /var/log/containers/*.log
            processors:
              - add_cloud_metadata: {}
              - add_docker_metadata: {}
              - add_kubernetes_metadata:
                  host: ${NODE_NAME}
                  matchers:
                    - logs_path:
                        logs_path: /var/log/containers/
        output.elasticsearch:
          hosts: ["https://elasticsearch:9200"]
      daemonSet:
        podTemplate:
          spec:
            automountServiceAccountToken: true
            containers:
              - name: filebeat
                volumeMounts:
                  - name: varlogcontainers
                    mountPath: /var/log/containers
                  - name: varlogpods
                    mountPath: /var/log/pods
                  - name: varlibdockercontainers
                    mountPath: /var/lib/docker/containers
                env:
                  - name: POD_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: NODE_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: spec.nodeName
            securityContext:
              runAsUser: 0
            serviceAccount: filebeat-container-logs
            volumes:
              - name: varlogcontainers
                hostPath:
                  path: /var/log/containers
              - name: varlogpods
                hostPath:
                  path: /var/log/pods
              - name: varlibdockercontainers
                hostPath:
                  path: /var/lib/docker/containers

# To deploy a Kibana instance
# For more settings, see https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-kibana.html
kibana:
  name: kibana
  labels:
    Environment: dev
  spec:
    # Disable generation of self-signed certificates
    disableTls: true
    # Number of Kibana nodes in this nodeSet
    count: 1
    # The Elasticsearch instance Kibana should try to connect to.
    elasticsearchRef:
      name: elasticsearch

virtualService:
  kibana:
    name: kibana
    type:
      # - VirtualService
      # - AuthorizationPolicy
    gateways:
      - default/default-gateway
    hosts:
      - kibana.internal.dev.reservoir.tools
    destination:
      host: kibana-kb-http
      portNumber: 5601
    whiteListed:
      ips: []
      matchLabels:
        common.k8s.elastic.co/type: kibana
      # releaseNamespace: true
      # internalIPs: []
  elasticsearch:
    name: elasticsearch
    type:
    gateways:
      - default/default-gateway
    hosts:
      - elasticsearch.internal.dev.reservoir.tools
    destination:
      host: elasticsearch-es-http
      portNumber: 9200
    whiteListed:
      ips: []
      matchLabels:
        common.k8s.elastic.co/type: elasticsearch

datadogMonitors:
  []
  # - name: test
  #   spec:
  #     query: "max(last_5m):max:elasticsearch.unassigned_shards{cluster_name:dev-applications} > 50"
  #     type: "query alert"
  #     name: "Elasticsearch Unassigned Shards test"
  #     message: "@ofir@unevenlabs.com  @filipe@unevenlabs.com"
  #     tags:
  #       - "test:datadog"
  #     priority: 5
  #     options:
  #       thresholds:
  #         critical: "50"
