name: release microservice
on: 
  push:
    branches:
      - master
    paths:
      - 'stable/microservice/**'
  release:
    types: [published, created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: ./.github/actions/helm-gh-pages
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: stable/microservice
